/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/ys/ys.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Yasuo = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./ys/yasuo.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
  useEffect( ()=>{
    actions[names[15]].reset().fadeIn(0.5).play();
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="SkinnedMesh">
        <group name="skinned_mesh">
          <skinnedMesh castShadow name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.Big_Sword} skeleton={nodes.mesh_0.skeleton} />
          <skinnedMesh castShadow name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={materials.Big_Spikes} skeleton={nodes.mesh_0_1.skeleton} />
          <skinnedMesh castShadow name="mesh_0_2" geometry={nodes.mesh_0_2.geometry} material={materials.Small_Spikes} skeleton={nodes.mesh_0_2.skeleton} />
          <skinnedMesh castShadow name="mesh_0_3" geometry={nodes.mesh_0_3.geometry} material={materials.Body} skeleton={nodes.mesh_0_3.skeleton} />
          <skinnedMesh castShadow name="mesh_0_4" geometry={nodes.mesh_0_4.geometry} material={materials.Small_Sword} skeleton={nodes.mesh_0_4.skeleton} />
          <skinnedMesh castShadow name="mesh_0_5" geometry={nodes.mesh_0_5.geometry} material={materials.Small_Sword_Blade} skeleton={nodes.mesh_0_5.skeleton} />
          <skinnedMesh castShadow name="mesh_0_6" geometry={nodes.mesh_0_6.geometry} material={materials.HeadB} skeleton={nodes.mesh_0_6.skeleton} />
          <skinnedMesh castShadow name="mesh_0_7" geometry={nodes.mesh_0_7.geometry} material={materials.HeadA} skeleton={nodes.mesh_0_7.skeleton} />
          <skinnedMesh castShadow name="mesh_0_8" geometry={nodes.mesh_0_8.geometry} material={materials.Spikes} skeleton={nodes.mesh_0_8.skeleton} />
          <skinnedMesh castShadow name="mesh_0_9" geometry={nodes.mesh_0_9.geometry} material={materials.FireBro} skeleton={nodes.mesh_0_9.skeleton} />
          <skinnedMesh castShadow name="mesh_0_10" geometry={nodes.mesh_0_10.geometry} material={materials.FireBro2} skeleton={nodes.mesh_0_10.skeleton} />
          <skinnedMesh castShadow name="mesh_0_11" geometry={nodes.mesh_0_11.geometry} material={materials.FireBro3} skeleton={nodes.mesh_0_11.skeleton} />
          <skinnedMesh castShadow name="mesh_0_12" geometry={nodes.mesh_0_12.geometry} material={materials.FireBro4} skeleton={nodes.mesh_0_12.skeleton} />
          <primitive object={nodes.Root_Upper} />
          <primitive object={nodes.Root_Lower} />
          <primitive object={nodes.Sword_World} />
          <primitive object={nodes.Sheath_World} />
          <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
          <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
          <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
          <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
          <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
          <primitive object={nodes.Buffbone_Cstm_Trail_3} />
          <primitive object={nodes.Buffbone_Cstm_Trail_2} />
          <primitive object={nodes.Buffbone_Cstm_Trail_1} />
          <primitive object={nodes.Fire_Root} />
          <primitive object={nodes.Fire_Root_2} />
          <primitive object={nodes.Fire_Root_3} />
          <primitive object={nodes.Fire_Root_4} />
          <primitive object={nodes.TestJoint} />
        </group>
      </group>
    </group>
  )
}

export default Yasuo

useGLTF.preload('./ys/yasuo.glb');
